
server:
  port: 8201
  servlet:
    context-path: /test-service
env-number: 2
config-test: 1112

spring:
  application:
    name: testservice
  # 环境 dev|test|prod
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 10.130.80.35:8848
        cluster-name: BJ # 配置集群名字
        namespace: dev-rong_env
  #        namespace: ${spring.profiles.active}_env

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.myproject.models.testservice.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    #  控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
