server:
  port: 8200

spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # gateway 可以从 nacos 发现微服务
      routes:
        - id: testservice
          uri: lb://testservice
#          uri: http://localhost:8201
          predicates:
            - Path=/test-service/**
        - id: demoservice
          uri: lb://demoservice
          #          uri: http://localhost:8201
          predicates:
            - Path=/demo-service/**
#      default-filters: # 全局过滤器
#        - AddRequestHeader=Truth, Global is Ok！
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true #解决options请求被拦截的问题
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: false # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

